ALTER TABLE transactions CHANGE wallet_id from_wallet_id BIGINT NOT NULL;
ALTER TABLE transactions CHANGE transaction_type type VARCHAR(20) NOT NULL;
ALTER TABLE transactions MODIFY transaction_date TIMESTAMP NOT NULL;
ALTER TABLE transactions MODIFY amount DECIMAL(19, 4) NOT NULL;
ALTER TABLE transactions ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE categories ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
